--CREATE OR ALTER PROCEDURE [dbo].[usp_JournalEntry_GetById]
--    @Id INT
--AS
--BEGIN
--    SET NOCOUNT ON;
    
--    SELECT 
--        Id,
--        Date,
--        Description,
--        CreatedAt,
--        UpdatedAt
--    FROM 
--        JournalEntries
--    WHERE 
--        Id = @Id;
--END